name: Playwright Tests

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start Next.js server in the background
        run: npm run dev &
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3000

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: npm run test:e2e

